"""Phase 3 step 3: Sage cross-validation for the new Magma InitialIdeal(I, w)
intrinsic (package-groebner-fan.mag). Re-computes the same initial ideal under
the same weight vector in Sage, asserts the leading-monomial sets agree.

The Sage analog of Magma's matrix-order `weight` constructor is a polynomial
ring with TermOrder via a matrix. Sage's TermOrder('M', matrix) does this.
Both use the convention: row 1 = w, remaining rows = lex tie-breaker.

Test fixtures (from test_initial_ideal_intrinsic.mag):
  - Raw-chain I^[3] = <f, f'> with f = x'' + x'y + y, f' = D(f), in the
    tightened 8-variable interleaved ring QQ[x00, y00, x01, y01, x02, y02, x03, y03].
  - L3-cone 0 interior weight, shifted to non-negative: (0,0,9,0,20,0,15,0).
    Expected initial ideal generators (per Magma): {x02, x03}.
  - L3-cone 5 interior weight, shifted: (0,0,10,5,0,0,0,0).
    Expected: {x01*y01, y00*x01, y01*x02}  (= {$.3*$.4, $.2*$.3, $.4*$.5}).

Run independently of Magma; the EXPECTED values are baked in as the
regression assertions.

Inputs:  no external files. Sage 10.8.
Outputs: per weight: initial-ideal generators + PASS/FAIL against expected.
Runtime: <0.5 s.
Memory:  project_slice3_sticky_result.md, project_lineality_in_sticky_check.md.
"""

from sage.all import PolynomialRing, QQ, TermOrder, matrix, ZZ


def init_ring(w, pivot):
    """Build an 8-variable QQ ring whose monomial order is the matrix order
    with row 1 = w and remaining rows = e_i for i != pivot (lex tie-break)."""
    n = len(w)
    rows = [list(w)]
    for i in range(1, n + 1):
        if i == pivot:
            continue
        rows.append([1 if j == i else 0 for j in range(1, n + 1)])
    M = matrix(ZZ, rows)
    T = TermOrder(M)
    var_names = ['x00', 'y00', 'x01', 'y01', 'x02', 'y02', 'x03', 'y03']
    S = PolynomialRing(QQ, 8, names=var_names, order=T)
    return S


def initial_ideal(w):
    """Build the raw-chain I^[3] in QQ[x00,...,y03] with matrix order = (w, lex tie)
    and return the initial ideal (= ideal of leading monomials of GB)."""
    # Pick the same pivot rule as Magma's InitialIdeal: first index i with w[i] > 0.
    pivot = next(i for i in range(1, len(w) + 1) if w[i - 1] > 0)
    S = init_ring(w, pivot)
    x, y, xp, yp, xpp, ypp, xppp, yppp = S.gens()
    f = xpp + xp * y + y
    fp = xppp + xpp * y + xp * yp + yp
    I = S.ideal([f, fp])
    gb = I.groebner_basis()
    lms = [g.lm() for g in gb]
    In = S.ideal(lms)
    return S, In, lms


def test_one(w, expected_LMs, label):
    S, In, lms = initial_ideal(w)
    # Compare as ideals (canonical, order-independent): the ideal generated by
    # Sage's LMs must equal the ideal generated by the expected LM strings.
    expected_polys = [S(s) for s in expected_LMs]
    got_ideal = S.ideal(lms)
    exp_ideal = S.ideal(expected_polys)
    ok = (got_ideal == exp_ideal)
    print(f"--- {label} ---")
    print(f"  w = {w}")
    print(f"  pivot = {next(i for i in range(1, len(w)+1) if w[i-1] > 0)}")
    print(f"  Sage LMs:  {[str(lm) for lm in lms]}")
    print(f"  expected:  {expected_LMs}")
    print(f"  {'PASS' if ok else 'FAIL'} (ideal equality)")
    return ok


def main():
    print("Sage cross-validation against Magma's InitialIdeal intrinsic.")
    print("=" * 64)
    all_pass = True

    # L3-cone 0 interior weight (shifted to non-negative).
    all_pass &= test_one(
        [0, 0, 9, 0, 20, 0, 15, 0],
        expected_LMs=['x02', 'x03'],
        label='L3-cone 0 (Magma → {x02, x03})')

    # L3-cone 5 interior weight (shifted).
    all_pass &= test_one(
        [0, 0, 10, 5, 0, 0, 0, 0],
        expected_LMs=['x01*y01', 'x01*y00', 'x02*y01'],
        label='L3-cone 5 (Magma → {x01*y01, x01*y00, x02*y01})')

    # Invariance under shift: w_a and w_a + k*h must give the same initial.
    h = [0, 1, 0, 2, 1, 0, 2, 0]  # diff-homogeneity direction
    w_a = [0, 0, 9, 0, 20, 0, 15, 0]
    w_a_shift = [w_a[i] + 7 * h[i] for i in range(8)]
    print()
    print(f"=== Invariance test (shift by 7 * h) ===")
    _, _, lm_a = initial_ideal(w_a)
    _, _, lm_a_shift = initial_ideal(w_a_shift)
    same = sorted(str(m) for m in lm_a) == sorted(str(m) for m in lm_a_shift)
    print(f"  w_a        LMs: {sorted(str(m) for m in lm_a)}")
    print(f"  w_a + 7h   LMs: {sorted(str(m) for m in lm_a_shift)}")
    print(f"  {'PASS' if same else 'FAIL'} — shift invariance")
    all_pass &= same

    print()
    print("=" * 64)
    print(f"OVERALL: {'ALL PASS' if all_pass else 'SOME FAILED'}")
    assert all_pass, "regression in InitialIdeal vs Sage cross-check"


if __name__ == '__main__':
    main()
